import SidebarWrapper from "@/components/dashboard/SidebarWrapper";
import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "../globals.css";

const geistMono = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} antialiased`}>
        <SidebarWrapper>{children}</SidebarWrapper>
      </body>
    </html>
  );
}
